# Generated by Django 4.0.6 on 2022-09-23 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('min_salary', models.CharField(max_length=100)),
                ('max_salary', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('job_desc', models.TextField()),
                ('no_of_vacancy', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date', models.DateField()),
                ('logo', models.ImageField(upload_to='pics')),
                ('c_website', models.URLField()),
                ('c_overview', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer_app.category')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer_app.experience')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer_app.jobtype')),
            ],
        ),
    ]
