# Generated by Django 4.0.6 on 2022-09-28 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employer_app', '0003_joblist_email_joblist_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='cv')),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer_app.joblist')),
            ],
        ),
    ]
