# Generated by Django 4.0.6 on 2022-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0004_appliedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedlist',
            name='status',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
