# Generated by Django 4.0.6 on 2022-10-10 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=0, max_length=15)),
                ('ptitle', models.CharField(max_length=255)),
                ('linkedlin', models.URLField()),
                ('objective', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('education_institute', models.CharField(max_length=255)),
                ('ecourse', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('cgpa', models.CharField(default=0, max_length=255)),
                ('field', models.CharField(default=0, max_length=255)),
                ('exp_title', models.CharField(max_length=255)),
                ('exp_company', models.CharField(max_length=255)),
                ('exp_place', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=255)),
                ('end_year', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('pro_pic', models.ImageField(upload_to='pics')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
    ]
