# Generated by Django 4.0.6 on 2022-10-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='field',
        ),
        migrations.AddField(
            model_name='resume',
            name='end_year2',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='exp_company2',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='exp_place2',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='exp_title2',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='m_college',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='m_end',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='m_location',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='m_start',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='masters_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_year2',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
