# Generated by Django 4.0.6 on 2022-10-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='comp_desc',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='country',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='district',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='found_year',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='employer',
            name='image',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='employer',
            name='no_of_employees',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='pin',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='employer',
            name='state',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='url',
            field=models.URLField(default=0),
        ),
    ]
